config/routes.rb
Rails.application.routes.draw do
  root "users#show",as: :home

  resource :user do
    get "sign_in" => "users#start"
    post "sign_in" => "users#sign_in"
    get "log_out"=> "users#log_out"
    resources :events
  end

  get "()" => "user#show"

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  validates :name,:start_time,presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :events,dependent: :destroy

  validates :email,:password,:password_confirmation,presence: true
  validates :password,confirmation: true

  validate :email,format: {with: Email.regexp}
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :require_login,except: [:start,:sign_in,:new,:create]

  protected 
    def require_login
      redirect_to sign_in_user_path unless current_user
    end
    def reset_session
      session[:id] = nil
    end

    def current_user
      @user ||= session[:id]&&User.find_by(id: session[:id])
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :event_belongs_to_user?,only: [:update,:destroy]
  before_action :current_user,only: [:create]

  def create
   @event = Event.new(event_params) 
   @event.user = @user

   if @event.save
     redirect_to home_path
   else
     render "users/show"
   end
  end

  def edit
    @event = Event.find_by(id: params[:id])
  end
  
  def update
   if @event.update_attributes(event_params)
     redirect_to user_path
   else
     render :edit
   end
  end

  def destroy
    @user.events.destroy(params[:id]) if @user.events.find_by(id: params[:id]) 
    redirect_to home_path
  end

  protected
    def event_params
      params.require(:event).permit(:name,:start_time,:repeat)
    end

    def event_belongs_to_user?
      redirect_to home_path unless @event = @user.events.find_by(id: params[:id]) 
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :current_user,only: [:show,:edit,:update] 
  after_action :reset_session,only: [:destoy,:log_out]

  def show 
    @event = Event.new
  end

  def start
  end

  def sign_in
    @user = User.find_by(sign_in_params)
    if @user
      session[:id] = @user.id
      redirect_to home_path
    else
      flash[:error] = "password or email wrong"
      render :start
    end
  end

  def new
   @user = User.new 
  end

  def create
    @user = User.create(sign_up_params)
    if @user.save
      session[:id] = @user.id
      redirect_to home_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(sing_up_params)
      flash[:notice] = "You seccessfull have updated yours profile"
      redirect_to :show
    else 
      render :edit
    end
  end

  def log_out
    redirect_to sign_in_user_path
  end

  def destroy
    @user.destroy
    redirect_to new_user_path
  end

    protected
      def sign_in_params
        params.require(:sign_in).permit(:email,:password)
      end
      def sign_up_params
        params.require(:user).permit(:email,:password,:password_confirmation,:name)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.haml
%br
=event.name
=event.start_time

app/views/events/_form.html.haml
=form_for @event,url: user_events_path(@event) do |f|
  =render "events/sub_form",f: f
  =f.submit :create

app/views/events/_sub_form.html.haml
=f.label :name
=f.text_field :name
=f.label :date
=f.text_field :start_time
=f.label :repeat
=f.select :repeat,[:none,:week,:year]

app/views/events/edit.html.haml
=form_for @event,url: {action: :update}do |f|
  =render "sub_form",f: f 
  =f.submit "edit"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calendar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/new.html.haml
=form_for @user,url: user_path(@user) do |f|
  =f.label :name
  %br
  =f.text_field :name
  %br
  =f.label :email
  %br
  =f.text_field :email
  %br
  =f.label :password
  %br
  =f.password_field :password
  %br
  =f.label :confirm_password
  %br
  =f.password_field :password_confirmation
  %br
  =f.submit "sign up"

app/views/users/show.html.haml
=@user.name
= calendar @user.events, {:start_day => :monday,:prev_text =>"prev", :next_text=>"next"} do |event| 
  %div= link_to event.name,edit_user_event_path(event),onclick: "appending(this);return false;"
#result
=render "events/form"

app/views/users/start.html.haml
%h6=flash[:error]
=form_for :sign_in,url: {controller: :users,action: :sign_in},method: :post do |f|
  =f.label :email
  %br
  =f.text_field :email
  %br
  =f.label :password
  %br
  =f.password_field :password
  %br
  =f.submit "sign in"